version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  fastapi:
    build:
      context: ./server
    container_name: fastapi-app
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - ./server/.env
    depends_on:
      - minio

volumes:
  minio_data: