name: noodle
description: "Flutter applications for file storing and organization"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.3
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.7
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mocktail: ^1.0.0
  http: ^1.1.0 
  flutter_lints: ^5.0.0

flutter:
  assets:
   - assets/images/logo.svg
   - assets/images/Account.svg
   - assets/images/Img_box.svg
   - assets/images/Back.svg
   - assets/images/File.svg
   - assets/images/folder.svg
   - assets/images/Plus.svg
   - assets/images/X.svg
   - assets/images/Profile_photo.png
   - assets/images/File_yellow.svg
   - assets/images/folder_filled.svg
   - assets/images/File_text.svg
   - assets/images/Menu.svg
   - assets/images/arrow_right.svg
   
  uses-material-design: true
  fonts:
    - family: Geologica
      fonts:
        - asset: assets/fonts/Geologica-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geologica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geologica-Thin.ttf
          weight: 100
        - asset: assets/fonts/Geologica-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Geologica_Cursive-Regular.ttf
          style: italic