name: Test Flutter

on:
  pull_request:
    branches:
      - main
    paths:
      - 'client/flutter_client/**'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        working-directory: client/flutter_client
        run: flutter pub get

      - name: Run tests
        working-directory: client/flutter_client
        run: flutter test